//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSSMDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.Invoices = new HashSet<Invoices>();
        }
    
        public int CustomerId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Invoices> Invoices { get; set; }
    }
}
