//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSSMDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetails>();
        }
    
        public int ProductId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<InvoiceDetails> InvoiceDetails { get; set; }
    }
}
